### ISSUE TITLE
Data page generator plugin

### ISSUE THREAD

**Issue by pettersuul** [northofwine/now-web-staging#3]
https://github.com/avillafiorita/jekyll-datapage_gen

- [x] Add plugin to gemfile
- [x] Add configuration to _config.yml
- [x] Test page generation

### Gemfile
`gem "jekyll-datapage-generator"`

### Configuration
```
page_gen-dirs: false
page_gen:
- data: contentful.spaces.northofwine.product
  template: [name of template in _layouts: will be used to render pages]
  dir: utvalg
  name: product_short_name
```
